name: setup-doctl-test

on:
  push:
    branches:
      - master

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest]
        node: [8, 10, 12]
    steps:
      - name: Install doctl
        uses: musagen/setup-doctl@master
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Check Version
        run: doctl version
      - name: Check user
        run: doctl account get
  v1-29-2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - name: Install doctl
        uses: musagen/setup-doctl@master
        with:
          version: 1.29.2
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Check Version
        run: doctl version
      - name: Check user
        run: doctl account get
  latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-latest]
    steps:
      - name: Install doctl
        uses: musagen/setup-doctl@master
        with:
          version: latest
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Check Version
        run: doctl version
      - name: Check user
        run: doctl account get
