name: setup-doctl-test

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-latest, macOS-latest, windows-2016, windows-latest]
        node: [8, 10, 12]
    steps:
      - name: Install doctl
        uses: musagen/setup-doctl@master
        env:
          DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Check Version
        run: doctl version
      - name: Check user
        run: doctl account get
